# Generated by Django 4.1.1 on 2022-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningData',
            fields=[
                ('date', models.IntegerField(primary_key=True, serialize=False, verbose_name='date')),
                ('mining_data', models.JSONField(verbose_name='mining_data')),
            ],
        ),
    ]
