# Generated by Django 4.1.1 on 2022-10-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiningData', '0002_currentprofit_minerdata_orderbookdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprofit',
            name='current_btc_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='current_btc_price'),
            preserve_default=False,
        ),
    ]
