# Generated by Django 4.1.1 on 2022-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiningData', '0003_currentprofit_current_btc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprofit',
            name='min_profit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='min_profit_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentprofit',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='strike_price'),
            preserve_default=False,
        ),
    ]
