# Generated by Django 4.1.1 on 2022-10-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiningData', '0004_currentprofit_min_profit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprofit',
            name='min_profit_price',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='min_profit_price'),
        ),
        migrations.AlterField(
            model_name='currentprofit',
            name='strike_price',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='strike_price'),
        ),
    ]
