# Generated by Django 4.1.1 on 2022-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiningData', '0005_alter_currentprofit_min_profit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashOrderData',
            fields=[
                ('order_id', models.TextField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('hash_order_data', models.JSONField(verbose_name='hash_order_data')),
            ],
        ),
    ]
